on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v2
        with:
          owner: ${{ github.repository_owner }}
          repo: npm-load
          package-name: npm-load
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          num-old-versions-to-delete: 100
          # min-versions-to-keep: 50
          # delete-only-pre-release-versions: false
